# This is a basic workflow to help you get started with Actions

name: Install Projects

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    name: Verify installs
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install Docksal
        run: curl -fsSL https://get.docksal.io | bash
      - name: fin sysinfo
        run: fin sysinfo
      - name: Set Docksal settings
        run: fin config set --global DOCKSAL_DNS_DISABLED=1
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Install Knot
        run: fin init

      # Runs a single command using the runners shell
      - name: Test Knot
        run: fin test

      # Runs a set of commands using the runners shell
      - name: fin config
        run: fin config
